# Generated by Django 2.1.7 on 2019-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20190223_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
