# Generated by Django 2.1.7 on 2019-03-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bots', '0002_bot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='accounts',
            field=models.ManyToManyField(related_name='bots', to='accounts.Account'),
        ),
    ]
