# Generated by Django 2.1.7 on 2019-02-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20190223_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
