# Generated by Django 2.1.7 on 2019-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0002_bot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('bots', models.ManyToManyField(related_name='following', to='bots.Bot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
